language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "nightly"

install: 
  - "pip install -r requirements.txt"

script:
  - robot --report=none --log=none --outputdir=tests/results --debugfile=debug.log tests/testcase.robot